<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-marcelarosalesj/blob/main/semana3_actividad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TC4029 Ciencia y analítica de datos

# Actividad 1 Semana 3
Profesor Jobish Vallikavungal

Alumna: Marcela Alejandra Rosales Jiménez

Matricula: A01032022

Fecha de entrega: 4 de Octubre de 2022


**Objetivo:** Entender los conceptos fundamentales de bases de datos, almacenes de datos, tipos de datos y realizar la limpieza de un conjunto de datos.

## Parte 1: Fundamentos de bases de datos

Revisa la página Lecturas del tema 3: Conceptos de almacenamiento y recuperación de información, y describe tus insights o entendimiento de cada uno de los subtemas: (Alrededor de 200 palabras)

1. Fundamentos de bases de datos y para ciencia de datos.  
2. Fundamentos de almacenes de datos (Data Warehouse) para ciencia de datos.

## Parte 2: Selección y limpieza de los Datos en Python

Para este actividad usa el base de datos encontrados por [aqui](https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/default%20of%20credit%20card%20clients.csv) su descripción [aqui](https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/dataset_info.txt). 

1. Revisa detenidamente la página [Ejercicio guiado para: Selección y limpieza de los Datos en Python](https://github.com/PosgradoMNA/Actividades_Aprendizaje-/blob/main/limpieza.ipynb).
2. En Google Colab ( = Jupyter notebook, o bien alguna otra IDE de su interés), escribe tu código para realizar la selección y limpieza de los datos como se indica en el ejercicio.
3. Ejecuta tu código.
4. Explica con tus palabras (documentas las lineas del codigo en celdas del Text) como funciona tu programa indicando lo que realizaste en la programación, en minimum palabras. 

## Parte 3: Preparación de los datos

Con base en los resultados de tu libreta de Google Colab de la Parte 2 responde detalladamente las siguientes preguntas: 

1. ¿Qué datos considero mas importantes? ¿Por qué?
2. ¿Se eliminaron o reemplazaron datos nulos? ¿Qué se hizo y por qué?
3. ¿Es necesario ordenar los datos para el análisis? Sí / No / ¿Por qué?
4. ¿Existen problemas de formato que deban solucionar antes del proceso de modelado? Sí / No / Por qué.
5. ¿Qué ajustes se realizaron en el proceso de limpieza de datos (agregar, integrar, eliminar, modificar registros (filas), cambiar atributos (columnas)?

Extensión: 400 palabras o más entre todas las respuestas. 

In [94]:
# Importar librarias necesarias para el análisis de datos
import pandas as pd
import numpy as np

In [95]:
# Definir ruta de archivo CSV y exportar los datos del dataset
data_path = "https://raw.githubusercontent.com/PosgradoMNA/Actividades_Aprendizaje-/main/default%20of%20credit%20card%20clients.csv"
df = pd.read_csv(data_path)
df.head()

ID      X1   X2   X3   X4    X5   X6   X7   X8   X9  ...      X15      X16  \
0   1   20000  2.0  2.0  1.0  24.0  2.0  2.0 -1.0 -1.0  ...      0.0      0.0   
1   2  120000  2.0  2.0  2.0  26.0 -1.0  2.0  0.0  0.0  ...   3272.0   3455.0   
2   3   90000  2.0  2.0  2.0  34.0  0.0  0.0  0.0  0.0  ...  14331.0  14948.0   
3   4   50000  2.0  2.0  1.0  37.0  0.0  0.0  0.0  0.0  ...  28314.0  28959.0   
4   5   50000  1.0  2.0  1.0  57.0 -1.0  0.0 -1.0  0.0  ...  20940.0  19146.0   

       X17     X18      X19      X20     X21     X22     X23    Y  
0      0.0     0.0    689.0      0.0     0.0     0.0     0.0  1.0  
1   3261.0     0.0   1000.0   1000.0  1000.0     0.0  2000.0  1.0  
2  15549.0  1518.0   1500.0   1000.0  1000.0  1000.0  5000.0  0.0  
3  29547.0  2000.0   2019.0   1200.0  1100.0  1069.0  1000.0  0.0  
4  19131.0  2000.0  36681.0  10000.0  9000.0   689.0   679.0  0.0  

[5 rows x 25 columns]

## Detalles sobre las columnas

X1: Amount of the given credit (NT dollar)

X2: Gender (1 = male; 2 = female). 

X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others). 

X4: Marital status (1 = married; 2 = single; 3 = others). 

X5: Age (year).

X6 - X11: History of past payment. Range -1 to 12 and above
- X6 = the repayment status in September, 2005
- X7 = the repayment status in August, 2005
- X8 = the repayment status in July, 2005
- X9 = the repayment status in June, 2005
- X10 = the repayment status in May, 2005
- X11 = the repayment status in April, 2005

X12-X17: Amount of bill statement (NT dollar).    
- X12 = amount of bill statement in September, 2005
- X13 = amount of bill statement in August, 2005
- X14 = amount of bill statement in July, 2005
- X15 = amount of bill statement in June, 2005
- X16 = amount of bill statement in May, 2005
- X17 = amount of bill statement in April, 2005

X18-X23: Amount of previous payment (NT dollar). 
- X18 = amount paid in September, 2005
- X19 = amount paid in August, 2005
- X23 = amount paid in July, 2005
- X18 = amount paid in June, 2005
- X19 = amount paid in May, 2005
- X23 = amount paid in April, 2005

## Limpieza de datos NaN

In [96]:
# Verifiquemos si falta algun dato
df.isnull().values.any()

True

In [97]:
# Verificar datos nulos por columna
df.isnull().any()

ID     False
X1     False
X2      True
X3      True
X4      True
X5      True
X6      True
X7      True
X8      True
X9      True
X10     True
X11     True
X12     True
X13     True
X14     True
X15     True
X16     True
X17     True
X18     True
X19     True
X20     True
X21     True
X22     True
X23     True
Y       True
dtype: bool

En casi todas las columnas falta al menos un dato.

Veamos cuántos renglones y columnas tiene el DataFrame.

In [98]:
print("Shape del DataFrame df: {}".format(df.shape))

Shape del DataFrame df: (30000, 25)


Un primer approach es eliminar las observaciones que tienen NaN en las columnas de X12 a X23 que corresponden al balance de los clientes.

Esto puede ser buena idea si no son demasiados registros.

In [99]:
df2 = df.dropna(subset=['X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23'])

In [100]:
print("Shape del DataFrame df2: {}".format(df2.shape))

Shape del DataFrame df2: (29974, 25)


In [101]:
print("Registros eliminados: {}".format(df.shape[0] - df2.shape[0]))

Registros eliminados: 26


Considero que eliminar 26 registros de 30,000 no es demasiado, representa un porcentaje pequeño del universo de datos.

In [110]:
percentage_eliminated = 26/30000*100.0
print(f"Porcentaje de elementos eliminados: {percentage_eliminated:2f} %")

Porcentaje de elementos eliminados: 0.086667 %


De aquí en delante se utilizará el DataFrame df2, el cual ya no tiene NaN en las columnas X12 a X23.

## Identificar Valores Atípicos 

In [106]:
cols = df2.columns.to_list()
print(cols)

['ID', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'Y']


Utilizamos la función unique para visualizar qué categorías únicas hay en las columnas del dataframe.

In [107]:
cols_h1 = ['ID', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11']
for col in cols_h1[1:]:
    print(f"{col}")
    print(df2[col].unique())

X1
[  20000  120000   90000   50000  500000  100000  140000  200000  260000
  630000   70000  250000  320000  180000  130000  450000   60000  230000
  160000  280000  360000   10000   40000  210000  150000  380000  310000
  400000   80000  290000  340000  300000   30000  240000  470000  480000
  350000  330000  110000  420000  170000  370000  270000  220000  190000
  510000  460000  440000  410000  490000  390000  580000  600000  620000
  610000  700000  670000  680000  430000  550000  540000 1000000  530000
  710000  560000  520000  750000  640000   16000  570000  590000  660000
  720000  327680  740000  800000  760000  690000  650000  780000  730000]
X2
[2. 1.]
X3
[2. 1. 3. 5. 4. 6. 0.]
X4
[1. 2. 3. 0.]
X5
[24. 26. 34. 37. 57. 29. 23. 28. 35. 51. 41. 30. 49. 39. 40. 27. 47. 33.
 32. 54. 58. 22. 31. 25. 46. 42. 43. 45. 56. 44. 53. 38. 63. 36. 52. 48.
 55. 60. 50. nan 61. 73. 59. 21. 67. 66. 62. 70. 72. 64. 65. 71. 69. 68.
 79. 75. 74.]
X6
[ 2. -1.  0. -2.  1.  3.  4.  8.  7.  5.  6.]


Para la segunda mitad de las columnas, al ser medidas en dólares, vamos a visualizar los datos de otra manera

In [109]:
cols_h2 = ['X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'Y']
for col in cols_h2[:-1]:
    print(f"{col}")
    print(f"* Min: {df2[col].min()}")
    print(f"* Max: {df2[col].max()}")

X12
* Min: -165580.0
* Max: 964511.0
X13
* Min: -69777.0
* Max: 983931.0
X14
* Min: -157264.0
* Max: 1664089.0
X15
* Min: -170000.0
* Max: 891586.0
X16
* Min: -81334.0
* Max: 927171.0
X17
* Min: -339603.0
* Max: 961664.0
X18
* Min: 0.0
* Max: 873552.0
X19
* Min: 0.0
* Max: 1684259.0
X20
* Min: 0.0
* Max: 896040.0
X21
* Min: 0.0
* Max: 621000.0
X22
* Min: 0.0
* Max: 426529.0
X23
* Min: 0.0
* Max: 528666.0


De lo anterior notamos los siguientes valores atipicos o incoherencias:

- X3: Tiene 0, 5, 6
- X4: Tiene 0
- X5: Tiene NaN
- X6-X11: Hay valores menores a -1

## Transformación de datos

Los valores atípicos identificados se van a transformar de la siguiente manera:
- X3 es la columna de educación, así que vamos a convertir los valores atipicos a la categoría 4 (`others`)
- X4 es el estado marital, así que vamos a convertir los valores atipicos a la categoría 3 (`others`)
- X5 es la edad, vamos a transformar los valores atipicos a una categoria extra -1 (`desconocido`)
- X6 a X11 es la columna de historial de pagos pasados. Para esta columna transformaremos el valor -1 (`pay duly`) a 0, para dejar a los valores atipicos como -1 (`desconocido`). Es decir, renombramos las categorías.

In [118]:
# Transformacion de columna X3
mask = (df2['X3'] == 0) | (df2['X3'] == 5 ) | (df2['X3'] == 6 ) | (df2['X3'].isna())
df2.iloc[mask] = 4

In [119]:
# Transformacion de columna X4
mask = (df2['X4'] == 0) | (df2['X4'].isna())
df2.iloc[mask] = 3

In [120]:
# Transformacion de columna X5
mask = (df2['X5'].isna())
df2.iloc[mask] = -1

In [127]:
# Transformacion de columnas X6 a X11
col_historial_pagos = ['X6', 'X7', 'X8', 'X9', 'X10', 'X11']
for col in col_historial_pagos:
    print(f"Transformando: {col}")
    # Transformar pay duly de -1 a 0
    mask = (df2[col] == -1)
    df2.iloc[mask] = 0
    # Transformar valores atipicos a -1
    mask = (df2[col] < 0) | (df2[col].isna())
    df2.iloc[mask] = -1

Transformando: X6
Transformando: X7
Transformando: X8
Transformando: X9
Transformando: X10
Transformando: X11


In [129]:
# Verificar transformación X6-X11
for col in col_historial_pagos:
    print(f"{col}")
    print(df2[col].unique())

X6
[ 0.  1.  2.  4.  3. -1.  8.  7.  5.  6.]
X7
[ 0.  2.  4.  3.  5. -1.  7.  1.  6.  8.]
X8
[ 0.  2.  4.  3. -1.  6.  7.  1.  5.  8.]
X9
[ 0.  2.  4.  3. -1.  5.  7.  6.  1.  8.]
X10
[ 0.  2.  4.  5.  3. -1.  7.  8.  6.]
X11
[ 0.  2.  4.  3.  6. -1.  7.  8.  5.]


In [131]:
df2.head()

ID     X1   X2   X3   X4    X5   X6   X7   X8   X9  ...      X15      X16  \
0   0      0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...      0.0      0.0   
1   0      0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...      0.0      0.0   
2   3  90000  2.0  2.0  2.0  34.0  0.0  0.0  0.0  0.0  ...  14331.0  14948.0   
3   4  50000  2.0  2.0  1.0  37.0  0.0  0.0  0.0  0.0  ...  28314.0  28959.0   
4   0      0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...      0.0      0.0   

       X17     X18     X19     X20     X21     X22     X23    Y  
0      0.0     0.0     0.0     0.0     0.0     0.0     0.0  0.0  
1      0.0     0.0     0.0     0.0     0.0     0.0     0.0  0.0  
2  15549.0  1518.0  1500.0  1000.0  1000.0  1000.0  5000.0  0.0  
3  29547.0  2000.0  2019.0  1200.0  1100.0  1069.0  1000.0  0.0  
4      0.0     0.0     0.0     0.0     0.0     0.0     0.0  0.0  

[5 rows x 25 columns]

## Visualización de datos 

In [ ]:
df2